# Generated by Django 3.1 on 2020-08-14 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('desc', models.TextField(max_length=3000)),
            ],
        ),
    ]
